### ISSUE TITLE
Responsive Layout: Bilder werden stark vergrößert

### ISSUE THREAD

**Issue by e-v-a-d** [TUM-MZ/creyoco#109]
Wenn man ein Bild in Creyoco einfügt und dabei eine bestimmte Zielgröße des Bildes angibt (Screenshot 1), wird das Bild auf einem großen Bildschirm richtig angezeigt (Screenshot 2).
Aber auf kleineren Bildschirmen wir dann die Einstellung der Zielgröße nicht mehr berücksichtigt und das Bild wird stark vergrößert (siehe Screenshot 3)

Bestimmung der Zielgröße:
![zielgroesse](https://cloud.githubusercontent.com/assets/11991924/9757448/f2775aea-56e0-11e5-83f5-822842802c06.png)

richtige Darstellung auf großem Bildschirm:
![bild1](https://cloud.githubusercontent.com/assets/11991924/9757469/24eef5a0-56e1-11e5-9d7b-1e53e8f4adb8.png)

falsche Darstellung auf kleinem Bildschirm:
![bild2](https://cloud.githubusercontent.com/assets/11991924/9757523/730552ca-56e1-11e5-9ae1-d49b06679244.png)

Muss man da in Creyoco weitere Einstellungen treffen, als nur die Zielgröße anzugeben?

Link: http://129.187.81.136/exeapp/package/96/1677/ (Account: admin)

**Comment by alendit** [comment]
We still need a way to make pictures responsive.
